OrdererOrgs:
- Name: Orderer
  Domain: example.com
  EnableNodeOUs: true
  Specs:
  - Hostname: orderer
    SANS:
    - localhost
    - 127.0.0.1
    - orderer.example.com
PeerOrgs:
- Name: Org1
  Domain: org1.example.com
  EnableNodeOUs: true
  Template:
    Count: 2
    SANS:
    - localhost
    - 127.0.0.1
    - '{.Hostname}.org1.example.com'
  Users:
    Count: 1
