

Deployment:
      ###########################
      ## the total number of orderer
      ###########################
      orderer: 1
      ###########################
      ## the total number of organization
      ###########################
      organization: 1
      ###########################
      ## the number of peer of each organization
      ###########################
      peer: 2
      ###########################
      ## the number of server/instance
      ###########################      
      server: 1
      ###########################
      ## configuration of blockchain node
      ## orderer, orderer2, orderer3, orderer4 ...
      ## peer0.org1, peer1.org1, peer0.org2, peer1.org2 ...
      ###########################  
      deployment:
          - Host: 1
            configuration:
              - 'peer0.org1'
              - 'peer1.org1'
              - 'orderer'

            ip: 10.0.0.1
      ###########################
      ## type of chaincode 
      ###########################  
      chaincode: 'fabcar'


