version: '3.7'
volumes:
  cli: {}
  peer0.org1.example.com: {}
  peer1.org1.example.com: {}
  orderer.example.com: {}
networks:
  test:
    name: testnet
    external: true
services:
  orderer.example.com:
    container_name: orderer.example.com
    image: hyperledger/fabric-orderer:2.2.5
    environment:
    - FABRIC_LOGGING_SPEC=INFO
    - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
    - ORDERER_GENERAL_LISTENPORT=7050
    - ORDERER_GENERAL_GENESISMETHOD=file
    - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
    - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
    - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
    - ORDERER_OPERATIONS_LISTENADDRESS=0.0.0.0:30000
    - ORDERER_GENERAL_TLS_ENABLED=true
    - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
    - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
    - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
    - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
    - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    volumes:
    - ../system-genesis-block/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../organizations/ordererOrganizations/example.com/orderers/orderer.example.com/msp:/var/hyperledger/orderer/msp
    - ../organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/:/var/hyperledger/orderer/tls
    - orderer.example.com:/var/hyperledger/production/orderer
    - ../configtx/:/var/hyperledger/config
    command: orderer
    ports:
    - 7050:7050
    - 30000:30000
    networks:
    - test
  peer0.org1.example.com:
    container_name: peer0.org1.example.com
    image: hyperledger/fabric-peer:2.2.5
    environment:
    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=testnet
    - FABRIC_LOGGING_SPEC=INFO
    - CORE_PEER_TLS_ENABLED=true
    - CORE_PEER_PROFILE_ENABLED=true
    - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
    - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
    - CORE_PEER_ID=peer0.org1.example.com
    - CORE_PEER_ADDRESS=peer0.org1.example.com:8100
    - CORE_PEER_LISTENADDRESS=0.0.0.0:8100
    - CORE_PEER_CHAINCODEADDRESS=peer0.org1.example.com:20100
    - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:20100
    - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org1.example.com:8101
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.example.com:8100
    - CORE_PEER_LOCALMSPID=Org1MSP
    - CORE_OPERATIONS_LISTENADDRESS=peer0.org1.example.com:32100
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    volumes:
    - /var/run/docker.sock:/host/var/run/docker.sock
    - ../organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp:/etc/hyperledger/fabric/msp
    - ../organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls:/etc/hyperledger/fabric/tls
    - peer0.org1.example.com:/var/hyperledger/production
    - ../configtx/:/var/hyperledger/config
    command: peer node start
    extra_hosts:
    - peer4.org1.example.com:10.0.0.3
    - peer2.org1.example.com:10.0.0.2
    - peer3.org1.example.com:10.0.0.2
    - peer5.org1.example.com:10.0.0.3
    ports:
    - 8100:8100
    - 20100:20100
    - 32100:32100
    networks:
    - test
  peer1.org1.example.com:
    container_name: peer1.org1.example.com
    image: hyperledger/fabric-peer:2.2.5
    environment:
    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=testnet
    - FABRIC_LOGGING_SPEC=INFO
    - CORE_PEER_TLS_ENABLED=true
    - CORE_PEER_PROFILE_ENABLED=true
    - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
    - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
    - CORE_PEER_ID=peer1.org1.example.com
    - CORE_PEER_ADDRESS=peer1.org1.example.com:8101
    - CORE_PEER_LISTENADDRESS=0.0.0.0:8101
    - CORE_PEER_CHAINCODEADDRESS=peer1.org1.example.com:20101
    - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:20101
    - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.example.com:8100
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.example.com:8101
    - CORE_PEER_LOCALMSPID=Org1MSP
    - CORE_OPERATIONS_LISTENADDRESS=peer1.org1.example.com:32101
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    volumes:
    - /var/run/docker.sock:/host/var/run/docker.sock
    - ../organizations/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/msp:/etc/hyperledger/fabric/msp
    - ../organizations/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/tls:/etc/hyperledger/fabric/tls
    - peer1.org1.example.com:/var/hyperledger/production
    - ../configtx/:/var/hyperledger/config
    command: peer node start
    extra_hosts:
    - peer4.org1.example.com:10.0.0.3
    - peer2.org1.example.com:10.0.0.2
    - peer3.org1.example.com:10.0.0.2
    - peer5.org1.example.com:10.0.0.3
    ports:
    - 8101:8101
    - 20101:20101
    - 32101:32101
    networks:
    - test
  cli:
    container_name: cli
    image: hyperledger/fabric-tools:2.2.5
    tty: true
    stdin_open: true
    environment:
    - GOPATH=/opt/gopath
    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    - FABRIC_LOGGING_SPEC=INFO
    - SYS_CHANNEL=system-channel
    - CORE_PEER_ID=cli
    - CORE_PEER_ADDRESS=peer0.org1.example.com:8100
    - CORE_PEER_LOCALMSPID=Org1MSP
    - CORE_PEER_TLS_ENABLED=true
    - CORE_PEER_PROFILE_ENABLED=true
    - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.crt
    - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.key
    - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt
    - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    volumes:
    - /var/run/:/host/var/run/
    - ../organizations:/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations
    - ../channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    - ../caliper-benchmarks:/opt/gopath/src/github.com/hyperledger/fabric/peer/caliper-benchmarks
    command: /bin/bash
    networks:
    - test
