test:
  workers:
    number: 10
  rounds:
    - label: Create a car.
      # 5000 transactions should create around 1000 cars per worker but not guaranteed
      # so need to set asset limits to less than 1000 for the other tests
      txNumber: 1000
      rateControl:
          type: fixed-rate
          opts:
            tps: 300
      workload:
        module: benchmarks/samples/fabric/fabcar/createCar.js
    - label: Create a car with payload 1000.
      # 5000 transactions should create around 1000 cars per worker but not guaranteed
      # so need to set asset limits to less than 1000 for the other tests
      txNumber: 1000
      rateControl:
          type: fixed-rate
          opts:
            tps: 300
      workload:
        module: benchmarks/samples/fabric/fabcar/createCar1000.js
    - label: Create a car with payload 4000.
      # 5000 transactions should create around 1000 cars per worker but not guaranteed
      # so need to set asset limits to less than 1000 for the other tests
      txNumber: 1000
      rateControl:
          type: fixed-rate
          opts:
            tps: 300
      workload:
        module: benchmarks/samples/fabric/fabcar/createCar4000.js
    - label: Create a car with payload 7000.
      # 5000 transactions should create around 1000 cars per worker but not guaranteed
      # so need to set asset limits to less than 1000 for the other tests
      txNumber: 1000
      rateControl:
          type: fixed-rate
          opts:
            tps: 300
      workload:
        module: benchmarks/samples/fabric/fabcar/createCar7000.js
    - label: Create a car with payload 10000.
      # 5000 transactions should create around 1000 cars per worker but not guaranteed
      # so need to set asset limits to less than 1000 for the other tests
      txNumber: 1000
      rateControl:
          type: fixed-rate
          opts:
            tps: 300
      workload:
        module: benchmarks/samples/fabric/fabcar/createCar10000.js
    - label: Create a car with payload 13000.
      # 5000 transactions should create around 1000 cars per worker but not guaranteed
      # so need to set asset limits to less than 1000 for the other tests
      txNumber: 1000
      rateControl:
          type: fixed-rate
          opts:
            tps: 300
      workload:
        module: benchmarks/samples/fabric/fabcar/createCar13000.js
    - label: Create a car with payload 16000.
      # 5000 transactions should create around 1000 cars per worker but not guaranteed
      # so need to set asset limits to less than 1000 for the other tests
      txNumber: 1000
      rateControl:
          type: fixed-rate
          opts:
            tps: 300
      workload:
        module: benchmarks/samples/fabric/fabcar/createCar16000.js
    - label: Create a car with payload 19000.
      # 5000 transactions should create around 1000 cars per worker but not guaranteed
      # so need to set asset limits to less than 1000 for the other tests
      txNumber: 1000
      rateControl:
          type: fixed-rate
          opts:
            tps: 300
      workload:
        module: benchmarks/samples/fabric/fabcar/createCar19000.js


    - label: Change car owner.
      txNumber: 1000
      rateControl:
          type: fixed-rate
          opts:
            tps: 300
      workload:
        module: benchmarks/samples/fabric/fabcar/changeCarOwner.js
        arguments:
          assets: 500
    - label: Change car owner with payload 1000.
      txNumber: 1000
      rateControl:
          type: fixed-rate
          opts:
            tps: 300
      workload:
        module: benchmarks/samples/fabric/fabcar/changeCarOwner1000.js
        arguments:
          assets: 500
    - label: Change car owner with payload 4000.
      txNumber: 1000
      rateControl:
          type: fixed-rate
          opts:
            tps: 300
      workload:
        module: benchmarks/samples/fabric/fabcar/changeCarOwner4000.js
        arguments:
          assets: 500
    - label: Change car owner with payload 7000.
      txNumber: 1000
      rateControl:
          type: fixed-rate
          opts:
            tps: 300
      workload:
        module: benchmarks/samples/fabric/fabcar/changeCarOwner7000.js
        arguments:
          assets: 500
    - label: Change car owner with payload 10000.
      txNumber: 1000
      rateControl:
          type: fixed-rate
          opts:
            tps: 300
      workload:
        module: benchmarks/samples/fabric/fabcar/changeCarOwner10000.js
        arguments:
          assets: 500
    - label: Change car owner with payload 13000.
      txNumber: 1000
      rateControl:
          type: fixed-rate
          opts:
            tps: 300
      workload:
        module: benchmarks/samples/fabric/fabcar/changeCarOwner13000.js
        arguments:
          assets: 500
    - label: Change car owner with payload 16000.
      txNumber: 1000
      rateControl:
          type: fixed-rate
          opts:
            tps: 300
      workload:
        module: benchmarks/samples/fabric/fabcar/changeCarOwner16000.js
        arguments:
          assets: 500
    - label: Change car owner with payload 19000.
      txNumber: 1000
      rateControl:
          type: fixed-rate
          opts:
            tps: 300
      workload:
        module: benchmarks/samples/fabric/fabcar/changeCarOwner19000.js
        arguments:
          assets: 500


    - label: Query all cars.
      txDuration: 10
      rateControl:
          type: fixed-rate
          opts:
            tps: 500
      workload:
        module: benchmarks/samples/fabric/fabcar/queryAllCars.js
        arguments:
          assets: 500
          startKey: '1'
          endKey: '50'

