name: Caliper test
version: 2.0.0
caliper:
  blockchain: fabric
channels:
- channelName: channel1
  contracts:
  - id: fabcar
  - id: fixed-asset
  - id: marbles
  - id: simple
  - id: smallbank
  - id: simple2
organizations:
- mspid: Org1MSP
  identities:
    certificates:
    - name: User1
      clientPrivateKey:
        path: ../organizations/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/keystore/priv_sk
      clientSignedCert:
        path: ../organizations/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/signcerts/User1@org1.example.com-cert.pem
  connectionProfile:
    path: ../organizations/peerOrganizations/org1.example.com/connection-org1.yaml
    discover: true
