Organizations:
- &id006
  Name: OrdererOrg
  ID: OrdererMSP
  MSPDir: ../organizations/ordererOrganizations/example.com/msp
  Policies:
    Readers:
      Type: Signature
      Rule: OR('OrdererMSP.member')
    Writers:
      Type: Signature
      Rule: OR('OrdererMSP.member')
    Admins:
      Type: Signature
      Rule: OR('OrdererMSP.admin')
  OrdererEndpoints:
  - orderer.example.com:7050
- &id008
  Name: Org1MSP
  ID: Org1MSP
  MSPDir: ../organizations/peerOrganizations/org1.example.com/msp
  Policies:
    Readers:
      Type: Signature
      Rule: OR('Org1MSP.admin', 'Org1MSP.peer', 'Org1MSP.client')
    Writers:
      Type: Signature
      Rule: OR('Org1MSP.admin', 'Org1MSP.client')
    Admins:
      Type: Signature
      Rule: OR('Org1MSP.admin')
    Endorsement:
      Type: Signature
      Rule: OR('Org1MSP.peer')
  AnchorPeers:
  - Host: peer0.org1.example.com
    Port: 8100
Capabilities:
  Channel:
    V2_0: true
  Orderer:
    V2_0: true
  Application:
    V2_0: true
Application:
  Organizations: null
  Policies: &id009
    Readers:
      Type: ImplicitMeta
      Rule: ANY Readers
    Writers:
      Type: ImplicitMeta
      Rule: ANY Writers
    Admins:
      Type: ImplicitMeta
      Rule: MAJORITY Admins
    LifecycleEndorsement:
      Type: ImplicitMeta
      Rule: MAJORITY Endorsement
    Endorsement:
      Type: ImplicitMeta
      Rule: MAJORITY Endorsement
  Capabilities:
    V2_0: true
Orderer:
  OrdererType: etcdraft
  Addresses: &id003
  - orderer.example.com:7050
  EtcdRaft: &id004
    Consenters:
    - Host: orderer.example.com
      Port: 7050
      ClientTLSCert: ../organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.crt
      ServerTLSCert: ../organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.crt
  BatchTimeout: 0.5s
  BatchSize: &id005
    MaxMessageCount: 50
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB
  Organizations: null
  Policies: &id007
    Readers:
      Type: ImplicitMeta
      Rule: ANY Readers
    Writers:
      Type: ImplicitMeta
      Rule: ANY Writers
    Admins:
      Type: ImplicitMeta
      Rule: MAJORITY Admins
    BlockValidation:
      Type: ImplicitMeta
      Rule: ANY Writers
Channel:
  Policies: &id001
    Readers:
      Type: ImplicitMeta
      Rule: ANY Readers
    Writers:
      Type: ImplicitMeta
      Rule: ANY Writers
    Admins:
      Type: ImplicitMeta
      Rule: MAJORITY Admins
  Capabilities: &id002
    V2_0: true
Profiles:
  TwoOrgsOrdererGenesis:
    Policies: *id001
    Capabilities: *id002
    Orderer:
      OrdererType: etcdraft
      Addresses: *id003
      EtcdRaft: *id004
      BatchTimeout: 0.5s
      BatchSize: *id005
      Organizations:
      - *id006
      Policies: *id007
      Capabilities:
        V2_0: true
    Consortiums:
      SampleConsortium:
        Organizations:
        - *id008
  TwoOrgsChannel:
    Policies: *id001
    Capabilities: *id002
    Consortium: SampleConsortium
    Application:
      Organizations:
      - *id008
      Policies: *id009
      Capabilities:
        V2_0: true
